"""Delete accounts left behind by the integration suite. DEV only.

Why this is a script and not a fixture
--------------------------------------
Test teardown cannot do this, and spent twenty-five PRs failing at it silently.

`profiles.id` references `auth.users` `ON DELETE CASCADE`, and every user-owned
table cascades from there. But `system_events`, `care_events` and the health
tables carry `reject_mutation()` triggers that refuse DELETE outright - `FINAL
§1.5` says those rows are immutable, and the trigger means it. So the cascade
promises a deletion the trigger forbids, and deleting any account that ever
created a plant fails with:

    Table system_events is append-only; DELETE is not permitted.

The two rules cannot both hold, and immutability is the one that should win: the
product never physically deletes an account anyway (`FINAL §21` anonymises
instead), so the cascade is unreachable in normal use. What it broke was the test
suite, whose teardown swallowed the error and left 1,375 accounts behind.

Removing them needs the immutability triggers disabled for the duration, which
needs table ownership. That is a deliberate administrative act on a development
database - so it lives in a script that names the project it will touch and
refuses to run anywhere else, rather than in a fixture that runs a thousand times
a day.

Foreign-key cascades stay enabled throughout. `session_replication_role =
replica` would have been shorter and wrong: it disables the constraint triggers
that implement `ON DELETE CASCADE`, so it would leave orphaned rows pointing at
users that no longer exist.

Usage
-----
    uv run python scripts/purge_dev_test_accounts.py           # report only
    uv run python scripts/purge_dev_test_accounts.py --delete  # actually delete
"""

from __future__ import annotations

import argparse
import pathlib
import sys

import psycopg

# The DEV project, named so this cannot be pointed at production by editing an
# environment variable. A purge script that trusts its configuration is one
# mistyped `.env` away from being the worst tool in the repository.
DEV_REF = "ckwvjyxeennrknwjsujl"
POOLER_HOST = "aws-0-eu-central-1.pooler.supabase.com"

# Every address the suites generate. Bare `@plantcare.local` is deliberately
# excluded: those accounts were made by hand for browser review and someone signs
# in with them. The two prefixes are the exception - `waiting-` and `w2-` are
# generated by verification scripts, and eight of them had accumulated by PR 33,
# none ever signed into.
#
# A deny-list, not an allowlist of real accounts. Once the product has users, "keep
# these addresses" would delete the next person who registers; the cost is that a
# suite adopting a new naming convention goes unmatched, which is what
# `unclassified_accounts` in `scrub_dev_database.py` exists to surface.
TEST_EMAIL_PATTERNS = (
    "%@example.com",
    "%@example.test",
    "waiting-%@plantcare.local",
    "w2-%@plantcare.local",
)

# Two kinds of table block the delete, and the second was missed until the purge
# was first run for real (PR 32).
#
# The row-immutable ones refuse the DELETE that cascades from `auth.users`.
#
# The *content*-immutable ones are never deleted at all - they are the target of a
# foreign key declared `ON DELETE SET NULL`, so removing an account makes Postgres
# issue `UPDATE knowledge_versions SET published_by = NULL`, and the trigger
# refuses that too:
#
#     Column knowledge_versions.published_by is immutable once written;
#     create a new version instead.
#
# Which is correct - provenance is exactly what those triggers exist to protect.
# It only has to yield to delete a *test* account on a development database.
IMMUTABLE_TRIGGERS = [
    # Row-immutable: refuse the cascading DELETE.
    ("system_events", "system_events_immutable"),
    ("care_events", "care_events_immutable"),
    ("health_assessments", "health_assessments_immutable"),
    ("health_observations", "health_observations_immutable"),
    ("health_issues", "health_issues_immutable"),
    ("health_recommendations", "health_recommendations_immutable"),
    ("health_assessment_sources", "health_assessment_sources_immutable"),
    ("admin_audit_log", "admin_audit_log_immutable"),
    # Content-immutable: refuse the `ON DELETE SET NULL` the cascade performs.
    # Found with a query over pg_constraint rather than by guessing: every FK into
    # profiles/auth.users with confdeltype = 'n' whose table also carries an
    # immutability trigger.
    ("care_plan_versions", "care_plan_versions_content_immutable"),
    ("knowledge_versions", "knowledge_versions_content_immutable"),
]


# Constraint triggers that would fire while the cascade takes an assessment apart.
# Both assert an invariant about a *live* assessment - 1-4 images - which is
# meaningless while the assessment itself is being deleted.
CONSTRAINT_TRIGGERS = [
    ("health_assessment_images", "health_assessment_images_count"),
    ("health_assessments", "health_assessments_require_images"),
]

# Deleting an *account* never reaches these two, because the knowledge catalogue is
# not user-owned. Removing a *species* does, and `scripts/scrub_dev_database.py`
# needs them off. They live here rather than there so that every trigger this
# repository ever switches off is named in one file - the alternative is two lists
# that drift, and a purge that fails on the one trigger the other list knew about.
CATALOGUE_TRIGGERS = [
    ("knowledge_versions", "knowledge_versions_no_delete"),
    ("knowledge_sources", "knowledge_sources_immutable"),
]

# The one non-CASCADE foreign key that blocks a user delete. `plant_images` and
# `health_assessment_images` both cascade from the account, but by different paths
# - images from `user_id`, assessment images from `health_assessments` - and
# Postgres does not order the two, so it reached `plant_images` first and refused:
#
#     update or delete on table "plant_images" violates foreign key constraint
#     "health_assessment_images_plant_image_id_fkey"
#
# Found by listing every FK between public tables whose confdeltype is not 'c',
# rather than by discovering them one failed run at a time.
PRE_DELETE = """
delete from public.health_assessment_images
 where health_assessment_id in (
   select id from public.health_assessments
    where user_id in (select id from auth.users where {where})
 )
"""


def dsn() -> str:
    """The DEV connection string, with two independent safety checks.

    The password is read from `.env` rather than the environment because the
    application never opens a direct database connection - it goes through
    PostgREST - so there is no `Settings` field for it, and `STRUCTURE §6` bans
    reading `os.environ` anywhere but `settings.py`. The configured project URL
    is read through `Settings`, which is the point of that rule: the check that
    this is DEV uses the same value the application would.
    """
    from app.config.settings import get_settings

    if DEV_REF not in get_settings().supabase_url:
        sys.exit(f"configured Supabase project is not {DEV_REF}. Refusing to run.")

    env_path = pathlib.Path(__file__).resolve().parents[1] / ".env"
    password = ""
    if env_path.exists():
        for line in env_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("SUPABASE_DB_PASSWORD="):
                password = line.split("=", 1)[1].strip()
                break
    if not password:
        sys.exit("SUPABASE_DB_PASSWORD is not in .env; nothing to connect with.")

    return f"postgresql://postgres.{DEV_REF}:{password}@{POOLER_HOST}:5432/postgres"


def _where() -> str:
    return " or ".join(f"email like '{pattern}'" for pattern in TEST_EMAIL_PATTERNS)


def report(conn: psycopg.Connection) -> int:
    total = conn.execute(f"select count(*) from auth.users where {_where()}").fetchone()
    assert total is not None
    print(f"test accounts:          {total[0]}")

    for table in ("plants", "care_tasks", "care_events", "system_events", "health_assessments"):
        row = conn.execute(
            f"""
            select count(*) from public.{table}
             where user_id in (select id from auth.users where {_where()})
            """
        ).fetchone()
        assert row is not None
        print(f"  {table:<20} {row[0]}")
    return int(total[0])


def purge(conn: psycopg.Connection) -> int:
    """Delete in one transaction, with the immutability triggers off.

    One transaction so a failure halfway leaves nothing half-deleted, and so the
    triggers are re-enabled by the rollback if anything raises. They are also
    re-enabled explicitly on the success path, because relying on a rollback to
    restore a safety mechanism is not a safety mechanism.
    """
    with conn.transaction():
        for table, trigger in IMMUTABLE_TRIGGERS + CONSTRAINT_TRIGGERS:
            conn.execute(f"alter table public.{table} disable trigger {trigger}")

        # Break the one FK the cascade cannot order around, before it runs.
        conn.execute(PRE_DELETE.format(where=_where()))

        # Deliberately no `finally` around the delete. Postgres aborts the whole
        # transaction on the first error, so re-enabling the triggers here would
        # itself raise `InFailedSqlTransaction` - and that exception, thrown from
        # a finally block, *replaces* the real one. The first real run of this
        # script reported "current transaction is aborted" and said nothing about
        # the immutable column that actually refused.
        #
        # The triggers are restored regardless: `ALTER TABLE ... DISABLE TRIGGER`
        # is transactional in Postgres, so the rollback undoes it. Verified after
        # that failure - all eleven were still enabled.
        result = conn.execute(f"delete from auth.users where {_where()}")
        deleted = result.rowcount

        for table, trigger in IMMUTABLE_TRIGGERS + CONSTRAINT_TRIGGERS:
            conn.execute(f"alter table public.{table} enable trigger {trigger}")
    return deleted


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--delete", action="store_true", help="actually delete; default reports")
    args = parser.parse_args()

    conn = psycopg.connect(dsn(), connect_timeout=30, autocommit=True)
    try:
        found = report(conn)
        if not args.delete:
            print("\nreport only - pass --delete to remove them")
            return
        if not found:
            print("\nnothing to delete")
            return

        deleted = purge(conn)
        print(f"\ndeleted {deleted} accounts and everything that cascaded from them")

        left = conn.execute("select count(*) from public.profiles").fetchone()
        assert left is not None
        print(f"profiles remaining:     {left[0]}")
    finally:
        conn.close()


if __name__ == "__main__":
    main()
